### ISSUE TITLE
json marshal error when creating service

### ISSUE THREAD

**Issue by wesleykendall** [jackall3n/terraform-provider-render#2]
Thank you so much for creating a Render provider!

I'm using terraform 1.3.5 and get the following error for the `render_service` resource
```
render_service.web: Creating...
╷
│ Error: json: cannot unmarshal array into Go value of type types.Service
│
│   with render_service.web,
│   on main.tf line 60, in resource "render_service" "web":
│   60: resource "render_service" "web" {
│
╵
```

Here's what my terraform looks like:

```
variable "render_api_key" {
  type = string
  sensitive = true
}

variable "render_email" {
  type = string
}

provider "render" {
  api_key = var.render_api_key
  email = var.render_email
}

resource "render_service" "web" {
  name = "hello-world"
  repo = "https://github.com/FootingDev/hello-world"
  type = "web_service"
}
```

I wasn't sure what `type` to use for the service, so I just looked up the values the API accepts.

Am I doing anything wrong here? Is it possible I'm on an incompatible terraform version? Thanks for your help. 

I'd love to contribute to this project BTW. Still learning some of the fundamentals though

**Comment by jpulec** [comment]
@wesleykendall Took me a bit of digging but I believe this will happen when your create call fails with a bad request, and the the code tries to make a GET to `/services/<ID>` but `ID` is the empty string. You're likely missing required data, such as `service_details`, or my case it was `region` since I believe there's a bug in this provider that tries to send `region` as the empty string if it is not set.

**Comment by jackall3n** [comment]
Hi, 

Thanks @wesleykendall for reporting this (and @jpulec) for looking into it. It looks like my `client` is missing some error handling.

I've improved this locally and can see that @jpulec is correct, your service creation call is failing.

```sh
render_service.web: Creating...
╷
│ Error: {"message":"invalid region: . valid regions are: [oregon, frankfurt]"}
│ 
│   with render_service.web,
│   on main.tf line 15, in resource "render_service" "web":
│   15: resource "render_service" "web" {
│ 
╵
```

You'll need to add in a `service_details` block to your service:

```terraform 
resource "render_service" "web" {
  name = "hello-world"
  repo = "https://github.com/FootingDev/hello-world"
  type = "web_service"

  service_details {
    env = "node"
    region = "oregon"
  }
}
```

I'll improve the docs and deploy a new version with the better error handling for future issues
